### PR TITLE
Don't output pkg description if undefined

### PR DESCRIPTION
**Pull request by callumlocke**
See #12.

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't think having to pass a modified `pkg` object is a good solution. Would be better to add a `description` option that can be either a custom description or `false` to disable, like the `version` option.

**Comment by kevva** [comment]
> Would be better to add a description option that can be either a custom description or false to disable, like the version option.

:+1:

**Comment by callumlocke** [comment]
I agree, I'll update the PR

**Comment by callumlocke** [comment]
closing this in favour of #14

**Pull request closed without merging**
