### PR TITLE
Allow running meow() more than once

### PR DESCRIPTION
**Pull request by rstacruz**
Useful for tests.

### CODE REVIEW

**Comment by rstacruz** [comment]
Ahhh.. That's better.

**Comment by sindresorhus** [comment]
`loud-rejection` already does this check, but I've removed the trace warning about it being called multiple times. I assume that will fix it for you.

**Comment by rstacruz** [comment]
yes it does, thank you.

fwiw, my use case was trying to make my bins structured in this way:

```js
#!/usr/bin/node
/* bin/myapp.js */

function run (args) {
  meow({ ... })
}

module.exports = run
if (!module.parent) run(process.argv.slice(2))
```

...and then using it for tests as well.

**Comment by sindresorhus** [comment]
Btw, you can `require()` bin files? Node.js strips the hashbang, but I guess your way is a bit cleaner.

**Pull request closed without merging**
