### PR TITLE
Rename `camelcase` to `camelCase`

### PR DESCRIPTION
**Pull request by ulken**
Extreme nitpick, but to my knowledge `camelcase` is spelled `camel case` and thus `camelCase` in code. Aligns better with its definition too 😜.

### CODE REVIEW

**Comment by ulken** [comment]
Totally unrelated, but opening a new PR felt like too much:

I find the comments https://github.com/sindresorhus/meow/blob/d963c1f26d04733be5c6e311f0b86971dea8da42/index.js#L198 and https://github.com/sindresorhus/meow/blob/d963c1f26d04733be5c6e311f0b86971dea8da42/index.js#L201 superfluous. Reading the code tells me exactly that.

If you agree, I can remove them.

**Comment by sindresorhus** [comment]
Can you fix the merge conflict?

**Comment by sindresorhus** [comment]
I agree about the comments.

**Comment by ulken** [comment]
Sure. Will do tonight. And remove comments.

**Comment by ulken** [comment]
@sindresorhus Done

**Pull request merged**
