### PR TITLE
Failing test marked + funwithflags

### PR DESCRIPTION
**Pull request by aretecode**
-  🚩 swap minimist with [funwithflags](https://github.com/fluents/funwithflags)
- 👕 fix comment casing for lint rules
- 🚨 mark failing test that sets on `process.title`

### CODE REVIEW

**Comment by sindresorhus** [comment]
I don't want to switch from `minimist`. `minimist` is very mature and stable and I don't really see any upsides to this. Thanks for the suggestion though.

**Comment by aretecode** [comment]
@sindresorhus funwithflags is simply minimist updated with more tests added, converted to ava, more documentation, the api is 1:1 all tests are the same it is 125% faster.

**Comment by aretecode** [comment]
@sindresorhus that failing test marked in this pr is unrelated to any dependency change though, it happens with a fresh clone on node 7.10 - any idea why it is failing?

**Comment by sindresorhus** [comment]
I just don't see it being worth switching now. That's just churn for very little benefit. CLI flag parsing is not a bottleneck, so slightly better perf is not important.

> that failing test marked in this pr is unrelated to any dependency change though, it happens with a fresh clone on node 7.10 - any idea why it is failing?

No idea. I've skipped the test in master for now. I don't have time to look into it. Seems to only happen on Node.js 7. Works fine on Node.js 6 and 4.

**Comment by aretecode** [comment]
@sindresorhus understandable, thought I'd see if it was worth doing.

Yes that's why I added the 7 entry in travis.

Thanks for checking it :-)

**Pull request closed without merging**
