### PR TITLE
Add shortcut for resolving relative paths

### PR DESCRIPTION
**Pull request by denysdovhan**
I like meow and want to make it better.

In my own cli apps I often write `cwd`-method that resolves relative filenames and current working dir. So, I propose to add this feature into **meow**.

I've already written tests and desc for `cwd`-method, so please check my changes and merge if it'll be useful for everyone.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you provide an example of when you would need something like this?

**Comment by denysdovhan** [comment]
Of course.
[Here is example from textr-cli](https://github.com/denysdovhan/textr-cli/blob/dev/cli/index.js#L46-L52), that reads stdin or specified filename

**Comment by sindresorhus** [comment]
All those uses are moot, though. You can pass relative paths directly to any core method, including the `fs` methods. No need to resolve it first.

**Comment by denysdovhan** [comment]
Hmm. Sometimes I have problems with relative paths. Maybe it only my fault.

**Comment by sindresorhus** [comment]
Yeah, I'm gonna pass on this. I very seldom have the need to resolve my paths and when I do, it's only `path.resolve('.', filename)`.

**Comment by denysdovhan** [comment]
Okay, thanks.

**Pull request closed without merging**
