### PR TITLE
Add more tests

### LINKED ISSUE #5: Tests
Needs more tests.

Help much appreciated :)

### PR DESCRIPTION
**Pull request by kevva**
Should we maybe add some type checks for the options too?

Fixes #5.

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Should we maybe add some type checks for the options too?

Sure

-

I was thinking we add a real CLI check too, by spawning a fixture app to make sure it actually outputs the right thing in the terminal.

**Comment by kevva** [comment]
Added further tests with a fixture app too.

**Comment by sindresorhus** [comment]
Excellent, exactly what I was thinking :)

Can you fix the merge conflict?

**Comment by kevva** [comment]
Yup, fixed :).

**Pull request merged**
